### ISSUE TITLE
请教上行流量路径的问题

### ISSUE THREAD

**Issue by egg1234** [sduoduo233/commonweb#1]
按照你的示意图，上行流量是直接发送给commonweb服务器的，但是根据客户端的样板命令来看
-local 127.0.0.1:8081 -upUrl http://your_domain.com/up -downUrl http://your_domain.com/down
理论上上传和下载的your_domain.com域名都已经是经过cloudflare代理的，所以commonweb的客户端应该也是往cloudflare的代理ip发上传流量才是，因为命令也没有看到commonweb的客户端指定上传使用另外一个ip地址，请教一下这个commonweb的客户端是怎样直接把上传流量发给commonweb服务器的

谢谢！

**Comment by sduoduo233** [comment]
up url就是上传的地址，你把它改成原服务器的地址不就行了
